baseURL: https://www.selfiebuild.com/
languageCode: en-us
title: SelfieBuild
theme: refresh

assetDir: "static"
DefaultContentLanguage: en
disableKinds: ["RSS"]

# Option to specify that all links will be open in a new tab.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

params:
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 3 

  favicon: "/images/favicon.svg"

  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: true
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: true
  # option to specify the main colour of the theme
  mainColour: "#EB01A5"

  summary:
    # option to specify the default image in the summary list
    defaultImage : "/images/default_summary.jpg"
  
  loading:
    # option to specify the loading image
    image: "/images/loaders/hearts.svg"

  mainPage:
    fontFamily: "Playball" 

  sidebar:
    logo: "/images/logo.svg"
    fontFamily: "Open Sans" # "Open Sans"

  navbar:
    fontFamily: "Open Sans"
    showIcons: false
    
  pagNotFound:
    image: "/images/annette_404.png"
    title: 404 Page Not Found :(
    subtitle: This is not the page you were looking for...
    imageWidth: 500px

  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be: "none", "menu", "footer" or "menu+footer"
    linkPosition: "menu+footer" 
    # this options let you specify the text of the link to the homepage
    linkText: "Home"  
    # option to specify the title in the homepage
    title: SelfieBuild
    # option to specify the subtitle in the homepage
    subtitle: Follow our Journey from DIY enthusiasts to Self Builders. We will document ideas, planning, tips, products and the many things to remember when building your own home from the plans, the highs and lows along the way to the finished dream.
    # option to specify image in the homepage
    image: "/images/annette.png" # worker.svg 
    # option to specify the width of the image in the homepage
    imageWidth: 500px

  footer:
    logo: "/images/logo.svg"
    #email: 
    #  link: name.surname@domain.com
    #  title: My Email
    youTube: 
      link: channel/UCXJ9B1-LxqCfxuhjh2NOepw
      title: YouTube
    # facebook: 
    #   link: your.username
    #   title: Facebook
    # github: 
    #   link: username
    #   title: Github
    # twitter: 
    #    link: username
    #    title: Twitter
    # instagram: 
    #    link: username
    #    title: Instagram
    copyright: SelfieBuild - 2021
    legal: Opinions are my own. Nothing on this Site constitutes professional and/or financial advice. May contain affiliate links. Site uses Google Analytics.

 

